### ISSUE TITLE
Can kaolin-wisp run on Windows?

### ISSUE THREAD

**Issue by aoliao12138** [NVIDIAGameWorks/kaolin-wisp#12]
As the title. Thank you very much!

**Comment by 3a1b2c3** [comment]
https://github.com/NVIDIAGameWorks/kaolin-wisp/commit/ec5ef7b0088899326b368ed49cc61f391fa06f60 i only had to change like 5 lines , would be awesome to add
![image](https://user-images.githubusercontent.com/74843139/183900184-b24e0b87-ba3a-4f72-8711-ed67e22ae042.png)

**Comment by drunknbass** [comment]
I am having 2 errors on windows, related to
https://github.com/facebookresearch/pytorch3d/commit/cb170ac024a949f1f9614ffe6af1c38d972f7d48

what stack are you running?

**Comment by 3a1b2c3** [comment]
python 3.7, cuda 11.3

**Comment by 3a1b2c3** [comment]
https://github.com/3a1b2c3/kaolin-wisp-Windows/blob/main/requirements_working.txt

**Comment by tovacinni** [comment]
@3a1b2c3 Thanks for trying this out, this is super helpful to us! Super excited to hear it can work on Windows... we're hoping to run some tests on Windows and get this merged.

**Comment by 3a1b2c3** [comment]
Great. I asked for a license but havent hear back, i hope i will soon. I added point drawing to the PrimitivesPainter, i make pr for that

**Comment by 3a1b2c3** [comment]
Maybe i should have used my github email for the request?
