### ISSUE TITLE
Installation with CUDA 11.2

### ISSUE THREAD

**Issue by LouisSerrano** [NVIDIAGameWorks/kaolin-wisp#120]
Is it possible to install wisp for CUDA 11.2 ?

**Comment by orperel** [comment]
Hi @LouisSerrano , CUDA 11.2 is supported, you can follow the manual installation for kaolin (mostly `git clone` and `python setup.py develop`:
https://kaolin.readthedocs.io/en/latest/notes/installation.html#installation-from-source

If you're looking for a binary installation, have a look at the kaolin wheels matrix here:
https://kaolin.readthedocs.io/en/latest/notes/installation.html#quick-start-linux-windows
kaolin released binary wheels for CUDA 11.1 or CUDA 11.3, so alternatively you can opt for either versions instead.

The wisp installation should remain the same for all kaolin versions.

**Comment by LouisSerrano** [comment]
Ok I had to install CUDA 11.7 to install it properly, otherwise I had a warning with incompatible torch and cuda version during the installation of wisp. Thanks, it seems to work now !
