### ISSUE TITLE
Codebook implementation is not training properly

### ISSUE THREAD

**Issue by DomaradzkiMaciej** [NVIDIAGameWorks/kaolin-wisp#135]
Hi, I'm trying to train codebook model with the following command:
`WISP_HEADLESS=1 python3 app/nerf/main_nerf.py --config app/nerf/configs/nerf_codebook.yaml --dataset-path ../data/blender/lego --dataset-num-workers 4`
But after 50 epochs, PSNR is still around 9.  

![image](https://user-images.githubusercontent.com/56363057/227525515-3d8db7af-3f71-4038-b707-3c962e6bd800.png)

**Comment by orperel** [comment]
Hi @DomaradzkiMaciej !
The config you're using is for sparsely initialized grids (i.e. the RTMV dataset, which initializes the grid cells from RGBD data).

The lego data initializes a fully dense Codebook grid in this example, which takes way longer to optimize.

I just checked the codebook the V8 example and it seems to work fine: PSNR after 100 epochs should be ~27.75
