### ISSUE TITLE
Issues on Kaolin & Cython version

### ISSUE THREAD

**Issue by QhelDIV** [NVIDIAGameWorks/kaolin-wisp#15]
The kaolin-wisp library is very exciting!

However, during installation I encountered several problems.

First, it seems kaolin-wisp requires kaolin 0.12.0, since if it is version 0.11.0 an error about kaolin camera class will occur.

Second, when installing kaolin it constantly interrupt the installation since my Cython version doesn't match the specified version exactly.
However, my Cython version is "0.29.29" and the specified version is "0.29.20", which I think there are no major differences and should not be a blocker.
My solution is to comment out the version checker in the setup.py

**Comment by tovacinni** [comment]
Thanks for your interest in kaolin-wisp and the feedback! 

I think Clement addressed the Cython issue in Kaolin. I just updated the README for kaolin-wisp to more clearly specify that the minimum version requirement for kaolin is `0.12.0`. Hopefully both of these fixes addresses your issue.
