### ISSUE TITLE
closest_point function is not implemented

### ISSUE THREAD

**Issue by jskim-research** [NVIDIAGameWorks/kaolin-wisp#162]
When setting sample_tex = True in app/nglod/configs/nglod_triplanar.yaml and running app/nglod/main_nglod.py, the code asserts that "This function is not supported in the main branch. Please use ttakikaw/pysdf for this function." and stops running.

The problem occurred at following code (wisp/ops/mesh/closest_point.py)
```
import torch
import numpy as np

def closest_point(
    V : torch.Tensor, 
    F : torch.Tensor,
    points : torch.Tensor):

    assert False and "This function is not supported in the main branch. Please use ttakikawa/pysdf for this function."
```

As the assert said, I tried to find ttakikawa/pysdf.
But, I can't find that.

Could you please let me know where is the ttakikawa/pysdf?

**Comment by jskim-research** [comment]
I solved the problem.

There are 2 approaches.

1. Using closest_point() function in [trimesh library](https://github.com/mikedh/trimesh/blob/main/trimesh/proximity.py) (this takes a day when processing 250k points, so I need to find other faster way)
2. Modify mesh2sdf_gpu_fast_nopre() in  [kaolin-wisp code](https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/main/wisp/csrc/external/mesh2sdf_kernel.cu) to return closest triangle. Actually, the code first gets the closest triangle and point to calculate SDF. (this takes a few minutes) 

By following the second approach, the training seems working.

However, I'm not sure why developers did not implement this. Is this wrong approach to get closest_point?

**Comment by tovacinni** [comment]
Hi, thanks for this issue. Unfortunately the `closest_point` feature relies on some features we haven't been able to release yet... but the workaround that you mentioned should work. The second approach in particular seems like it would be useful to expose for everyone- would you be open to maybe submitting a PR for the fix you implemented?

Thanks!!!

**Comment by jskim-research** [comment]
Okay, I will submit a PR for the fix after cleaning up the code!

**Comment by tovacinni** [comment]
Thanks Jisoo!
