### ISSUE TITLE
How to convert nerf model to mesh

### ISSUE THREAD

**Issue by kevinhangoat** [NVIDIAGameWorks/kaolin-wisp#17]
First, thank you so much for this library! I am wondering is there yet a function that can convert a trained nerf model to the mesh (like the one in instant-ngp)? I look into the code and could not find it.

**Comment by 3a1b2c3** [comment]
Look for raymarching as a a starting point

**Comment by tovacinni** [comment]
Hi and thanks for your interest in our library!

We haven't implemented this but you should just be able to use a marching cubes implementation (like the one here: https://scikit-image.org/docs/stable/auto_examples/edges/plot_marching_cubes.html) to write a widget to export mesh by getting densities.

**Comment by Caenorst** [comment]
We currently have two solutions from Kaolin:
- Use [https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.conversions.html#kaolin.ops.conversions.marching_tetrahedra](our marching tetrahedra) with a tetrahedral mesh grid
- Use [our marching cube](https://kaolin.readthedocs.io/en/latest/modules/kaolin.ops.conversions.html#kaolin.ops.conversions.voxelgrids_to_trianglemeshes)
