### ISSUE TITLE
Whats the difference between cameras and image planes gizmos in gui?

### ISSUE THREAD

**Issue by 3a1b2c3** [NVIDIAGameWorks/kaolin-wisp#33]
Whats the difference between cameras and image planes in gui?
I would love to see image planes but they look pretty much the same to me now?
Just checking i dont miss anything before making myself some

![image](https://user-images.githubusercontent.com/74843139/187098347-f7ec43db-5db1-47b4-83e7-480903164751.png)

**Comment by orperel** [comment]
Cameras are drawn as vector data layers:
https://github.com/NVIDIAGameWorks/kaolin-wisp/tree/main/wisp/gfx/datalayers

These are drawn directly with OpenGL draw calls (as wisp gizmos):
https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/main/wisp/renderer/gizmos/ogl/primitives_painter.py

Imgui widgets are currently scoped to the gui window. 
If you're looking for painting gl 2d textures directly on the canvas, that's indeed in our near-term roadmap but contributions are always welcome 🙂

**Comment by 3a1b2c3** [comment]
I am currently adding debug calls for rays and octrees and ideally features so i can check my understanding of code.

**Comment by orperel** [comment]
Looking forward to it! 
For rendering "latent" features from within the network, you can also check out the SIGGRAPH demo here:
https://www.nvidia.com/en-us/on-demand/session/siggraph2022-sigg22-s-14/?playlistId=playList-92d9241d-6d4c-4fc7-88f6-eb8484008787

We haven't pushed the demo code yet, a light version of it should be published by next week.
