### ISSUE TITLE
error C2398: element '2': conversion from 'unsigned __int64' to '_Ty' requires a narrowing conversion

### ISSUE THREAD

**Issue by zh-en520** [NVIDIAGameWorks/kaolin-wisp#34]
hello!Thanks for the great project!
I'm having a problem configuring the project environment. 
------------------------------------------------------------------------------>
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\stdint.h(21): note:See declaration of "int64_t"
wisp/csrc\ops\hashgrid_interpolate.cpp(49): error C2398: element '2': conversion from 'unsigned __int64' to '_Ty' requires a narrowing conversion
with
         [
             _Ty=int64_t
         ]
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl .exe' failed with exit status 2
above!
////////////////////////////////////////////////////////////////////////////////////
above!
my environment is：
windows11
python=3.8
pytorch=1.11.0
cuda=11.3
gpu=NVIDIA GeForce GTX 1650
I followed the README.md instructions exactly and installed steps 1-6 successfully. Error in step 7.
can you tell me what to do？

**Comment by 3a1b2c3** [comment]
https://github.com/NVIDIAGameWorks/kaolin-wisp/pull/28

**Comment by zh-en520** [comment]
I still get errors using https://github.com/3a1b2c3/kaolin-wisp-Windows. What I'm trying to say is that once I run 'python setup.py develop' I get the same error, either https://github.com/NVIDIAGameWorks/kaolin or https://github.com/3a1b2c3/kaolin-wisp -Windows.
Is there any workaround?
Here is what went wrong:
===================================================================》》》》》》》》》
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(540): note: see instantiation of the alias template being compiled "c10::OptionalBase<c10 ::impl::VirtualGuardImpl>" reference
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/core/impl/InlineStreamGuard.h(232): note: see instantiation of the class template being compiled "c10::optional" <T>" reference
        with
        [
            T=c10::impl::VirtualGuardImpl
        ]
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/core/StreamGuard.h(162): note: see instantiation of the class template being compiled "c10::impl:: Reference to InlineMultiStreamGuard<c10::impl::VirtualGuardImpl>"
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(432): warning C4624: "c10::trivially_copyable_optimization_optional_base<T>": destructor already Implicitly defined as "deleted"
        with
        [
            T=c10::impl::VirtualGuardImpl
        ]
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(198): warning C4624: "c10::constexpr_storage_t<T>": destructor already Implicitly defined as "deleted"
        with
        [
            T=std::vector<c10::ivalue::Future::WeakStorage,std::allocator<c10::ivalue::Future::WeakStorage>>
        ]
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(397): note: see instantiation of the class template being compiled "c10::constexpr_storage_t<T >" reference
        with
        [
            T=std::vector<c10::ivalue::Future::WeakStorage,std::allocator<c10::ivalue::Future::WeakStorage>>
        ]
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(540): note: see instantiation of the class template being compiled "c10::trivially_copyable_optimization_optional_base<T >" reference
        with
        [
            T=std::vector<c10::ivalue::Future::WeakStorage,std::allocator<c10::ivalue::Future::WeakStorage>>
        ]
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(540): note: see instantiation of the alias template being compiled "c10::OptionalBase<std ::vector<c10::ivalue::Future::WeakStorage, std::allocator<c10::ivalue::Future::WeakStorage>>>"
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\ATen/core/ivalue_inl.h(834): note: see instantiation of the class template being compiled "c10::optional<std ::vector<c10::ivalue::Future::WeakStorage, std::allocator<c10::ivalue::Future::WeakStorage>>>"
D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\c10/util/Optional.h(432): warning C4624: "c10::trivially_copyable_optimization_optional_base<T>": destructor already Implicitly defined as "deleted"
        with
        [
            T=std::vector<c10::ivalue::Future::WeakStorage,std::allocator<c10::ivalue::Future::WeakStorage>>
        ]

**Comment by zh-en520** [comment]
Continuing the question above:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc.exe -c wisp/csrc\external\mesh2sdf_kernel.cu -o build\temp.win-amd64-3.8\Release\wisp/csrc \external\mesh2sdf_kernel.obj -ID:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include -ID:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\torch \csrc\api\include -ID:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include\TH -ID:\downloads\anaconda\envs\wisp\lib\site-packages\torch\include \THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" -ID:\downloads\anaconda\envs\wisp\include -ID:\downloads\anaconda\envs\wisp\include " -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community \VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits \10\include\10.0.19041.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt" "-IC:\Program Files (x86 )\Windows Kits\10\include\10.0.19041.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_dll_suppress=base_interface_compiler /compiler wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME =_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --use-local-env
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin\\nvcc.exe' failed with exit status 1

**Comment by zh-en520** [comment]
#https://github.com/NVIDIAGameWorks/kaolin/issues/482
When I "pip install ninja", the above error is no longer reported, and everything is back on track. The problem encountered after that is very similar to the one described in this link. I can't compile all the .obj's. I believe if I'm on ubuntu maybe I can configure it successfully, but I only want to use it on windows. Is there any solution?

**Comment by Caenorst** [comment]
Hi @zh-en520 , can you post the full logs? I can't see the FAIL from what you provided. Have you been able to build Kaolin on your system?

**Comment by zh-en520** [comment]
@Caenorst thank you for reading. 
No, I can`t build Kaolin and build Kaolin-wisp. 
Build Kaolin error::---------------------->>>>>>>>>>>>>>>>>>>>
(wisp) D:\nv\kaolin-wisp-Windows-main1\kaolin>python setup.py develop
Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
running develop
D:\downloads\anaconda\envs\wisp\lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\downloads\anaconda\envs\wisp\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing kaolin.egg-info\PKG-INFO
writing dependency_links to kaolin.egg-info\dependency_links.txt
writing requirements to kaolin.egg-info\requires.txt
writing top-level names to kaolin.egg-info\top_level.txt
reading manifest file 'kaolin.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'kaolin.egg-info\SOURCES.txt'
running build_ext
minimum_required_version= (19, 0, 24215)
compiler_info= b'\xd3\xc3\xd3\xda x64 \xb5\xc4 Microsoft (R) C/C++ \xd3\xc5\xbb\xaf\xb1\xe0\xd2\xeb\xc6\xf7 19.29.30146 \xb0\xe6\r\n\xb0\xe6\xc8\xa8\xcb\xf9\xd3\xd0(C) Microsoft Corporation\xa1\xa3\xb1\xa3\xc1\xf4\xcb\xf9\xd3\xd0\xc8\xa8\xc0\xfb\xa1\xa3\r\n\r\n\xd3\xc3\xb7\xa8: cl [ \xd1\xa1\xcf\xee... ] \xce\xc4\xbc\xfe\xc3\xfb... [ /link \xc1\xb4\xbd\xd3\xd1\xa1\xcf\xee... ]\r\n'
version= ['19', '29', '30146']
building 'kaolin._C' extension
minimum_required_version= (19, 0, 24215)
compiler_info= b'\xd3\xc3\xd3\xda x64 \xb5\xc4 Microsoft (R) C/C++ \xd3\xc5\xbb\xaf\xb1\xe0\xd2\xeb\xc6\xf7 19.29.30146 \xb0\xe6\r\n\xb0\xe6\xc8\xa8\xcb\xf9\xd3\xd0(C) Microsoft Corporation\xa1\xa3\xb1\xa3\xc1\xf4\xcb\xf9\xd3\xd0\xc8\xa8\xc0\xfb\xa1\xa3\r\n\r\n\xd3\xc3\xb7\xa8: cl [ \xd1\xa1\xcf\xee... ] \xce\xc4\xbc\xfe\xc3\xfb... [ /link \xc1\xb4\xbd\xd3\xd1\xa1\xcf\xee... ]\r\n'
version= ['19', '29', '30146']
Emitting ninja build file D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" /LIBPATH:D:\downloads\anaconda\envs\wisp\libs /LIBPATH:D:\downloads\anaconda\envs\wisp\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart_static.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit__C D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\bindings.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\metrics\sided_distance.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\metrics\unbatched_triangle_distance.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\packed_simple_sum.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\tile_to_packed.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\conversions\mesh_to_spc\mesh_to_spc.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\conversions\unbatched_mcube\unbatched_mcube.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\mesh\mesh_intersection.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\convolution.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\feature_grids.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\point_utils.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\query.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\spc.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\mesh\deftet.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\mesh\dibr_soft_mask.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\mesh\rasterization.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\spc\raytrace.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\metrics\sided_distance_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\metrics\unbatched_triangle_distance_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\packed_simple_sum_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\tile_to_packed_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\conversions\mesh_to_spc\mesh_to_spc_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\conversions\unbatched_mcube\unbatched_mcube_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\mesh\mesh_intersection_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\convolution_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\feature_grids_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\generate_points.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\minkowski_conv.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\point_utils_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\query_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\ops\spc\scan_octrees.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\mesh\deftet_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\mesh\dibr_soft_mask_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\mesh\rasterization_cuda.obj D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\render\spc\raytrace_cuda.obj /OUT:build\lib.win-amd64-3.8\kaolin\_C.pyd /IMPLIB:D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin/csrc\_C.lib
LINK : fatal error LNK1181: cannot open input file:“D:\nv\kaolin-wisp-Windows-main1\kaolin\build\temp.win-amd64-3.8\Release\kaolin\csrc\bindings.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

(wisp) D:\nv\kaolin-wisp-Windows-main1\kaolin>

**Comment by zh-en520** [comment]
I installed Kaolin by accident before, and now I can use Kaolin. But it fails to install again
(wisp) D:\nv\kaolin-wisp-Windows-main1>python -c "import kaolin; print(kaolin.__version__)"
0.12.0

(wisp) D:\nv\kaolin-wisp-Windows-main1>

**Comment by zh-en520** [comment]
The following is the result of running Kaolin-wisp:
(wisp) D:\nv\kaolin-wisp-Windows-main1>python setup.py develop
running develop
D:\downloads\anaconda\envs\wisp\lib\site-packages\setuptools\command\easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\downloads\anaconda\envs\wisp\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing wisp.egg-info\PKG-INFO
writing dependency_links to wisp.egg-info\dependency_links.txt
writing top-level names to wisp.egg-info\top_level.txt
reading manifest file 'wisp.egg-info\SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'wisp.egg-info\SOURCES.txt'
running build_ext
minimum_required_version= (19, 0, 24215)
compiler_info= b'\xd3\xc3\xd3\xda x64 \xb5\xc4 Microsoft (R) C/C++ \xd3\xc5\xbb\xaf\xb1\xe0\xd2\xeb\xc6\xf7 19.29.30146 \xb0\xe6\r\n\xb0\xe6\xc8\xa8\xcb\xf9\xd3\xd0(C) Microsoft Corporation\xa1\xa3\xb1\xa3\xc1\xf4\xcb\xf9\xd3\xd0\xc8\xa8\xc0\xfb\xa1\xa3\r\n\r\n\xd3\xc3\xb7\xa8: cl [ \xd1\xa1\xcf\xee... ] \xce\xc4\xbc\xfe\xc3\xfb... [ /link \xc1\xb4\xbd\xd3\xd1\xa1\xcf\xee... ]\r\n'
version= ['19', '29', '30146']
building 'wisp._C' extension
minimum_required_version= (19, 0, 24215)
compiler_info= b'\xd3\xc3\xd3\xda x64 \xb5\xc4 Microsoft (R) C/C++ \xd3\xc5\xbb\xaf\xb1\xe0\xd2\xeb\xc6\xf7 19.29.30146 \xb0\xe6\r\n\xb0\xe6\xc8\xa8\xcb\xf9\xd3\xd0(C) Microsoft Corporation\xa1\xa3\xb1\xa3\xc1\xf4\xcb\xf9\xd3\xd0\xc8\xa8\xc0\xfb\xa1\xa3\r\n\r\n\xd3\xc3\xb7\xa8: cl [ \xd1\xa1\xcf\xee... ] \xce\xc4\xbc\xfe\xc3\xfb... [ /link \xc1\xb4\xbd\xd3\xd1\xa1\xcf\xee... ]\r\n'
version= ['19', '29', '30146']
Emitting ninja build file D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2.git.kitware.jobserver-1
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\downloads\anaconda\envs\wisp\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\lib/x64" /LIBPATH:D:\downloads\anaconda\envs\wisp\libs /LIBPATH:D:\downloads\anaconda\envs\wisp\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart_static.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib /EXPORT:PyInit__C D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\bindings.obj D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\external\mesh_to_sdf.obj D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\ops\hashgrid_interpolate.obj D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\render\find_depth_bound.obj D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\external\mesh2sdf_kernel.obj D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\ops\hashgrid_interpolate_cuda.obj D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\render\find_depth_bound_cuda.obj /OUT:build\lib.win-amd64-3.8\wisp\_C.pyd /IMPLIB:D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp/csrc\_C.lib
LINK : fatal error LNK1181: 无法打开输入文件“D:\nv\kaolin-wisp-Windows-main1\build\temp.win-amd64-3.8\Release\wisp\csrc\external\mesh2sdf_kernel.obj”
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181

(wisp) D:\nv\kaolin-wisp-Windows-main1>python -c "import kaolin; print(kaolin.__version__)"
0.12.0

(wisp) D:\nv\kaolin-wisp-Windows-main1>

**Comment by Caenorst** [comment]
Ok let's start with Kaolin first, do you mind opening a new issue on Kaolin repo for reference for other users? :)

**Comment by zh-en520** [comment]
Ok, no problem

**Comment by tovacinni** [comment]
Does this still fail with the new merged PR (https://github.com/NVIDIAGameWorks/kaolin-wisp/pull/28)?

**Comment by zh-en520** [comment]
@tovacinni It doesn't fail anymore, we have to match enough correct cuda and torch versions to take effect
https://github.com/NVIDIAGameWorks/kaolin/issues/617

**Comment by orperel** [comment]
Closing this issue, feel free to reopen if needed
