### ISSUE TITLE
Is occupancy grid utilized in NeRF implementation?

### ISSUE THREAD

**Issue by kevinhangoat** [NVIDIAGameWorks/kaolin-wisp#40]
Hi, in the instant-ngp paper, there is an occupancy grid updated and used in NeRF ray marching. But I think this is not implemented yet in wisp? Would you mind give more details about difficulties when implementing it and why it cannot work? Thank you so much.

**Comment by tovacinni** [comment]
The occupancy grid is used and you can find it here: https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/main/wisp/models/nefs/nerf.py#L81
