### ISSUE TITLE
ImportError: cannot import name 'parse_options' from 'wisp.config_parser'

### ISSUE THREAD

**Issue by robo-warrior2** [NVIDIAGameWorks/kaolin-wisp#54]
Obtaining this error while trying to test NGLOD:

```
(wisp) PS E:\Projects\kaolin-wisp> python app\main.py --config configs\nglod_nerf.yaml --dataset-path .\data\V8 --dataset-num-workers 4
Traceback (most recent call last):
  File "app\main.py", line 14, in <module>
    from wisp.config_parser import parse_options, argparse_to_str, get_modules_from_config, \
ImportError: cannot import name 'parse_options' from 'wisp.config_parser' (e:\projects\kaolin-wisp\wisp\config_parser.py)
```

**Comment by salykovaa** [comment]
Same problem, cannot run demo app

**Comment by salykovaa** [comment]
@robo-warrior2 try to use ``` app\main_multiview.py ``` or ```  app\main_sdf.py ```  instead of ``` app\main.py```. It solved my problem

**Comment by Caenorst** [comment]
Hi @robo-warrior2 @salykovaa looks like I broke some of the main / README / demo / template, I'm reverting back until everything is solved, you can use `app/main.py` again.
