### ISSUE TITLE
Config parser does not support FunnyNeuralField when running the latent nerf example

### ISSUE THREAD

**Issue by royorel** [NVIDIAGameWorks/kaolin-wisp#88]
Great work on this library!!

One issue I encountered is that the config parser does not support the FunnyNeuralField class in the latent nerf example. It raises a value error and the example can't run. Simply adding FunnyNeural Field to the parser won't work since it has no __init__ function and the base_nef __init__ function won't initialize it properly.

https://github.com/NVIDIAGameWorks/kaolin-wisp/blob/d118afd8bc40557e75754aa2e587c1a0d3ec8fd2/wisp/config_parser.py#L586-L614

**Comment by orperel** [comment]
Hi @royorel ! Thanks for reporting this one!
We have a new version that fixes that and revises the demo which should be up very soon

**Comment by orperel** [comment]
@royorel 
Should be fixed now with #91 

We also simplified the demo a bit to make it more "beginner friendly", but the hard-coded settings also reduce the output quality a bit (for the time being).
